<div class="panel panel-default">
  <div class="panel-body">
    <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Inserir Dataframe | <a class="btn btn-info"  href="<?= PATH ?>/admin/dataframes">Voltar</a></div>
  <div class="panel-body">


	  <form  action="<?= PATH ?>/admin/dataframes/add" method="POST">
  	  <input type="hidden" id="data_frame_csv" name = "data_frame_csv" value="llalaal">
	  <div class="form-group">
	    <label for="exampleInputEmail1">Titulo</label>
	    <input name = 'titulo' type="text" class="form-control" id="exampleInputEmail1" placeholder="Titulo">
	  </div>
	 
	  <div class="form-group">
	    <label for="exampleInputFile">Inserir Dataframe</label>
	      <div id="inputs" class="clearfix">
			    <input type="file" id="files" name="files[]" multiple />
			  </div>
			  <hr />
			  <output id="list">
			  </output>
			  <hr />
			  <table id="contents" style="width:100%; height:300px; overflow: vertical;" border class="table" >
			  </table>
	    <p class="help-block">Inserir Arquivo no formato CSV</p>
	  </div>
	  <input type="submit" class="btn btn-success"></input>
	</form>
    
  </div>

  
  </div>
  
</div>


</div>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
  <script src="http://evanplaice.github.io/jquery-csv/src/jquery.csv.min.js"></script>
    <script src="<?= PATH ?>/public/js/csvtojson.js"></script>
  <!-- <script src="<?= PATH ?>/public/js/jquery.min.js"></script> -->





