<div class="panel panel-default">
  <div class="panel-body">
    <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Inserir Dataframe | <a href="<?= PATH ?>/admin/dataframes">Voltar</a></div>
  <div class="panel-body">

	  <form  action="<?= PATH ?>/admin/dataframes/add" method="POST">
	  <div class="form-group">
	    <label for="exampleInputEmail1">Titulo</label>
	    <input name = 'titulo' type="text" class="form-control" id="exampleInputEmail1" placeholder="Titulo">
	  </div>
	 
	  <div class="form-group">
	    <label for="exampleInputFile">Inserir Dataframe</label>
	    <input type="file" id="exampleInputFile">
	    <p class="help-block">Inserir Arquivo no formato CSV</p>
	  </div>
	  <input type="submit" class="btn btn-default"></input>
	</form>
    
  </div>

  
  </div>
  
</div>


</div>



