<div class="panel panel-default">
  <div class="panel-body">
  	
    <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Meus DataFrames | <a href="">Adicionar</a></div>
  <div class="panel-body">
    
  </div>

  
  
  	<table class="table"> 
  		<thead>
  			<tr> 
  				<th>#</th> 
  				<th>Titulo</th> 
  				<th>Criado em</th> 
  				<th>Ações</th> 
  				</tr> 
  		</thead> 
  		<tbody> 
  			<tr> 
  				<th scope="row">1</th> 
  				<td>Salário dos trabalhadores</td> 
  				<td>17/06/2018</td> 
  				<td><a href="">Analisar | </a><a href="">Alterar | </a><a href="">Deletar</a></td> 
  			</tr> 
  		</tbody> 
  	</table>
    
  
  </div>
  
</div>


</div>


