<div class="panel panel-default">
  <div class="panel-body">
  	
    <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Meus DataFrames | <a href="<?= PATH?>/admin/dataframes/add">Adicionar</a></div>
  <div class="panel-body">
    
  </div>
  
  	<table class="table"> 
  		<thead>
  			<tr> 
  				<th>#</th> 
  				<th>Titulo</th> 
  				<th>Criado em</th> 
  				<th>Ações</th> 
  				</tr> 
  		</thead> 
  		<tbody> 
        <?php
           for($i = 0; $i < count($data); ++$i) {
            
         ?>
  			<tr> 
  				<th scope="row">1</th> 
  				<td><?=  $data[$i]['titulo']  ?>  </td> 
  				<td><?= date('d/m/Y', strtotime($data[$i]['created_at'])); ?> ?></td> 
  				<td><a href="<?= PATH?>/admin/dataframes/analytic/<?=  $data[$i]['id']  ?>">Analisar | <a href="<?= PATH?>/admin/dataframes/edit/<?=  $data[$i]['id']  ?>" >Alterar | </a><a href="<?= PATH?>/admin/dataframes/delete/<?=  $data[$i]['id']  ?>" >Deletar</a></td> 
  			</tr>

        <?php 
            }
          

         ?> 
  		</tbody> 
  	</table>
    
  
  </div>
  
</div>


</div>


