<div class="panel panel-default">
  <div class="panel-body">
    <div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Análise de dados do Datafrane  | <a class="btn btn-info"  href="<?= PATH ?>/admin/dataframes">Voltar</a></div>
  <div class="panel-body">
  	<h3>Colunas <span class="label label-default"><?= $matriz['colunas'] ?></span></h3>
  	<h3>Linhas <span class="label label-default"><?= $matriz['linhas'] ?></span></h3>
    
  </div>

  
  </div>
  
</div>


</div>
