
  
  	
    <div class="panel panel-default">
  <!-- Default panel contents -->
  <center><h1>Meu perfil</h1></center>
  <div class="panel-body">
    
  </div>

  <?php 

	if(isset($sucesso)){
		echo 'Conta criada com sucesso';

	}

 ?>

  <div class="cadastro_">
	<br /><br />
	<center><form name="formulario" id="formulario_cadastro" action="<?= PATH?>/admin/perfil" method="post">
		<label>Nome: </label> <input type="text" name="name" value="<?=$_SESSION['name']?>" size="45" maxlength="150" /><br /> 
		<label>E-mail: </label> <input type="text" name="email" value="<?=$_SESSION['email']?>" size="45" maxlength="150" /> <br />
		<label>Senha </label> <input type="password" name="password" value="<?=$_SESSION['password']?>" size="45" maxlength="150" /><br />
		<input type="submit" name="botao-cadastrar" value="Alterar">
		<input type="reset" name="botao-apagar" value="Apagar">
   </form></center>



</div>
 </body>
</html>

    

