<html lang="pt-br">
<head>
  <title>Bem - vindo à Analitec</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/CSS" href="<?= PATH ?>/public/css/estilo.css">
  <link rel="stylesheet" type="text/CSS" href="<?= PATH ?>/public/css/estilogeral.css">
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<?= PATH ?>">Analitec</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="<?= PATH ?>">Home</a></li>
      <li><a href="<?= PATH ?>/quemsomos">Quem somos</a></li>
      <li><a href="<?= PATH ?>/contato">Contato</a></li>
    </ul>
	<ul class="nav navbar-nav navbar-right">

      <?php 
          if(isset($_SESSION[PREFIX . 'logado'])){
           

        
       ?>
      <li><a href="<?= PATH ?>/admin/perfil"><span class="glyphicon glyphicon-user"></span><?=$_SESSION['name']?></a></li>
      <li><a href="<?= PATH ?>/admin/logout"><span class="glyphicon glyphicon-log-in"></span> Sair</a></li>
      <?php
        }else{
        ?>
      <li><a href="<?= PATH ?>/cadastro"><span class="glyphicon glyphicon-user"></span> Cadastre-se</a></li>
      <li><a href="<?= PATH ?>/admin/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      <?php 
        }
       ?>
    </ul>
  </div>
  </div>
</nav>
 <div class="corpo preto">
  <div class="conteudo">