	<div class="login_">
	 <center><h1>Login</h1></center>
	 <?php 
	 	if(isset($erro)){
	 		echo $erro;

	 	}

	  ?>
	 <br /><br />
	   <center>	
		<form name="formulario" id="formulario_login" action="<?= PATH ?>/admin/login" method="post">
			<label>E-mail: </label> <input type="text" name="email" value="" size="45" maxlength="150" /> <br />
			<label>Senha </label> <input type="password" name="senha" value="" size="45" maxlength="150" /><br />
			<input type="submit" name="botao-login" value="Login">
			<input type="reset" name="botao-corrigir" value="Corrigir">
		</form>
	  </center>	
	</div>


