<html lang="pt-br">
<head>
  <title>Área de administração</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" type="text/CSS" href="<?= PATH ?>/public/css/estilo.css">
  <link rel="stylesheet" type="text/CSS" href="<?= PATH ?>/public/css/estilogeral.css">
  <script src="<?= PATH ?>/public/js/csvtoTable.js"></script>
  <script src="<?= PATH ?>/public/js/scripts.js"></script>

</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<?= PATH ?>">Analitec</a>
    </div>
    <ul class="nav navbar-nav">
    </ul>
	<ul class="nav navbar-nav navbar-right">
      <li class="active"><a href="<?= PATH ?>/admin/dataframes">Meus arquivos </a></li>
      <li><a href="<?= PATH ?>/admin/perfil"><span class="glyphicon glyphicon-user"></span><?=$_SESSION['name']?></a></li>
      <li><a href="<?= PATH ?>/admin/logout"><span class="glyphicon glyphicon-log-in"></span> Sair</a></li>
    </ul>
  </div>
  </div>
</nav>
 <div class="corpo preto">
  <div class="conteudo">