<div class="panel panel-default">
  <div class="panel-body">
  	
    <div class="panel panel-default">
  <!-- Default panel contents -->
  <center><h1>Cadastre-se e comece a usar!</h1></center>
  <div class="panel-body">
    
  </div>

  <?php 

	if(isset($sucesso)){
		echo 'Conta criada com sucesso';

	}

 ?>

  
  <div class="cadastro_">
	<br /><br />
	<center><form name="formulario" id="formulario_cadastro" action="" method="post">
		<label>Nome: </label> <input type="text" name="nome" value="Digite seu nome completo" size="45" maxlength="150" /><br /> 
		<label>E-mail: </label> <input type="text" name="email" value="Digite seu e-mail" size="45" maxlength="150" /> <br />
		<label>Senha </label> <input type="password" name="senha" value="Digite sua senha" size="45" maxlength="150" /><br />
		<input type="submit" name="botao-cadastrar" value="Cadastrar">
		<input type="reset" name="botao-apagar" value="Apagar">
   </form></center>



</div>
 </body>
</html>

    
  
  </div>
  
</div>


</div>

