  	
    <div class="panel panel-default">
  <!-- Default panel contents -->
  <center><h1>Cadastre-se e comece a usar!</h1></center>
  <div class="panel-body">
    
  </div>
  
  <div class="cadastro_">
	<br /><br />
	<center><form name="formulario" id="formulario_cadastro" action="<?= PATH ?>/perfil" method="post">
		<label>Nome: </label> <input type="text" name="name" size="45" maxlength="150" /><br /> 
		<label>E-mail: </label> <input type="text" name="email"  size="45" maxlength="150" /> <br />
		<label>Senha </label> <input type="password" name="password"  size="45" maxlength="150" /><br />
		<input type="submit" name="botao-cadastrar" value="Cadastrar">
		<input type="reset" name="botao-apagar" value="Apagar">
   </form></center>



</div>
 </body>
</html>

    

