<div class="corpo">
	<center><h2>Contato</h2></center>
</div>
<div class="corpo_principal">
	<br /><br />
	<p>Alameda Riacho Alto, 503<br /> Bairro Rio Negro - Porto Alegre - RS <br /> CEP:69918-662
	<br /><br />
	
	<p>+55 51 2208-0709
	<br />
	<p>contato@analitec.com.br
	
</div>
<div class="formulario">
	<br /><br />

<form name="formulario" id="formulario_contato" action="" method="post">
		<label>Nome: </label> <input type="text" name="nome" value="Digite seu nome completo" size="40" maxlength="150" /> 
		<label>E-mail: </label> <input type="text" name="email" value="Digite seu e-mail" size="45" maxlength="150" /> <br /><br />
		<label>Telefone: </label> <input type="text" name="telefone" value="Digite seu número de telefone" size="34" maxlength="150" />
		<label>Assunto: </label> <input type="text" name="assunto" value="Digite o assunto" size="46" maxlength="150" /><br /><br />
		<label>Mensagem: </label> <input type="text" name="mensagem" value="" style="height:60px" size="93" maxlength="500" /><br /><br />
		<input type="submit" name="botao-enviar" value="Enviar">
		<input type="reset" name="botao-apagar" value="Apagar">
   </form>



</div>

















