  <div class="corpo preto">
	<div class="conteudo">
		<div class="slide">
			<img src="<?= PATH ?>/public/img/imagem1.JPEG" alt="Imagem 1" title="Imagem 1" class="slideImagem">
			<img src="<?= PATH ?>/public/img/imagem2.PNG" alt="Imagem 2" title="Imagem 2" class="slideImagem">
			<img src="<?= PATH ?>/public/img/imagem3.jpg" alt="Imagem 3" title="Imagem 3" class="slideImagem">
		  <img src="<?= PATH ?>/public/img/imagem4.jpg" alt="Imagem 4" title="Imagem 4" class="slideImagem">
		</div>
	</div>
  </div>
  
<div class="corpo">
	<br /><br /><br /><br /><br />
  <center><h2>Bem - vindo(a) à Analitec!</h2></center>
</div>
<div class="texto_index" style="font-size: large">
	<br /><br />
	<center><p> Faça seu cadastro e conheça nossa ferramenta para análise de dados!</center>
	
</div>

