<html>
    <head>
        <title>Voltando</title>
        <script type="text/javascript" src="meuScript.js"></script>
    </head>
    <body>
        <div style="Background-color:#87CEFA;text-align:center">
        <p>Minha primeira div</p>
        </div>
        <div style="border:3px dotted #9F0">
        <p>Segunda Div</p>
        </div>
        <p>Hello!</p>
        
        <div id="estilo_aqui">
            <p> este é um experimento com div, vou estilizá-lo com CSS!</p>
            
            
        </div>
        
        
        
        
        
        
        <script type="text/javascript">
            alert("Seja bem-vindo ao meu teste!");
            
            /* var nome;
            nome = prompt('Qual seu nome? ');
            alert('Seja bem-vindo ' + nome); */
            
            /* var idade;
            idade = prompt('sua idade? ');
            alert('nome: ' + nome +
                  '\n idade: ' + idade); */
            /* var idade = prompt("Qual sua idade?: ");
            
            if (idade >= 18){
                alert("Ok, pode entrar");
            } else {
                alert("Feche a página ou será rastreado");
            } */
            
            
            
            </script>
        <button onclick="alert('Você clicou no botão');">Clique Aqui</button>
    </body>
</html>