<div class="testando">
	
	<center><h1>Sobre a Analitec</h1><br />
	<img src="<?= PATH ?>/public/img/quemsomos1.jpg" height="500" width="1000"></img>
	<br /><br />
	<div class="texto" style="font-size: large">
	<p font-size="25px">A Analitec originou-se da ideia de fornecer ao usuário uma ferramenta para análise de dados de fácil uso e compreensão. Nossa equipe <br />é composta por pessoas especializadas em análise e ciência de dados com um alto nível de comprometimento e profissionalismo.<br />
    Trabalhamos sob os principios de honestidade para com os dados de nossos clientes, inovação para tornar a ferramenta cada vez melhor, <br />um suporte de qualidade para a solução de problemas rapidamente,
	e garantir um serviço satisfatório.</p>
	</div>
</div>
